#!/bin/sh

# issue number tagging

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

branch_name=`git rev-parse --abbrev-ref HEAD`
issue_number=`echo ${branch_name} | cut -d '-' -f1`
first_line=`head -n1 ${COMMIT_MSG_FILE}`

if [[ ! -z $issue_number ]]; then
    sed -i ".bak" "1s/^/[#$issue_number] /" ${COMMIT_MSG_FILE}
 fi

# # JIRA ISSUE TAGGING
# #App Name
# APP_NAME="FA"

# if [ -z "$BRANCHES_TO_SKIP" ]; then
#   BRANCHES_TO_SKIP=(main develop release hotfix)
# fi

# BRANCH_NAME=$(git symbolic-ref --short HEAD)
# BRANCH_NAME="${BRANCH_NAME##*/}"
# JIRA_ID=`echo $BRANCH_NAME | egrep -o "$APP_NAME-[0-9]+"`

# BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
# BRANCH_IN_COMMIT=$(grep -c "$JIRA_ID" $1)

# if [ -n $JIRA_ID ] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then 
#   sed -i.bak -e "1s/^/$JIRA_ID /" $1
# fi