# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RIBsStudy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RIBsStudy
  pod 'RIBs'
  pod 'SnapKit'
  pod 'RxCocoa'

  target 'RIBsStudyTests' do
	inherit! :search_paths
  end
end
